
CREATE DATABASE TESEBADA;

USE TESEBADA;

CREATE TABLE dbo.Ventas
(
ID INT NOT NULL,
    PROD NVARCHAR(200) NOT NULL,
    CANTIDAD DECIMAL(10,4) NOT NULL,
    PRECIO MONEY  NOT  NULL,
    COSTO MONEY NOT NULL,
    VENTA INT NOT NULL,
    TS DATETIME NOT NULL,
    LINEA NVARCHAR(50) NOT NULL,
    CAJA NVARCHAR(10) NOT NULL,
CAJERO NVARCHAR(10) NOT NULL)

BULK INSERT VENTAS
FROM ''
WITH(
FIELDTERMINATOR = '\t',
ROWTERMINATOR = '\n',
FIRSTROW = 2);

